### PR TITLE
Change lab09

### PR DESCRIPTION
**Pull request by renaudwangler**
1. Remove auto password generation and InPrivate login to change it (it's now possible to set the users password when creating it)
2. Remove mention of using I.E. in the rdp session when not necessary since some students reported they were confused of the purpose
3. update the name of the user to leave in the Azure AD for its deletion

### CODE REVIEW

**Comment by polichtm** [comment]
1. The primary challenge with this approach that the password you specified will likely be (if it is not already) identified as too common - which make this instruction invalid.
2. You seem to be making the assumption that the lab VM has Microsoft Edge available. This might not be the case.
3. Valid point - updated separately
rgds
Marcin
3.

**Comment by renaudwangler** [comment]
1. I don't agree with your point since I tested it and used the password you actually instruct to change in a few lines later....

2. I just copy/pasted the instructions used all over the lab... I'm not the one assuming anything here ;)

Feeeling a little sorry to spend time to correct this lab (I teach on a regular basis) during the teaching just to see you simply disagree with the added value of some real students'ideas....



________________________________

**Comment by polichtm** [comment]
Your input is always appreciated...
Setting/updating passwords the Azure portal is a bit more restrictive than via PowerShell. We might want to consider simply asking students to set it to a value they choose - rather than providing one explicitly. 
Would you mind clarifying what about Internet Explorer did your students find confusing?
rgds
Marcin

**Comment by polichtm** [comment]
I incorporated the changes you suggested into the lab instructions. Let us know if you have any additional suggestions
rgds
Marcin

**Comment by renaudwangler** [comment]
Hi
Thank-you for listening so carefully to our field comments and suggestions.
To answer your previous question : this lab is not very light and I encoutered 2 students that asked me why they HAD TO connect to the azure portal from within the "Azure AD Connect" computer. By reading the lab instructions, I understood their concern. Maybe we should simply avoid being so specific about the computer and browser to usr for this check...

Once again, thank you for the value you see in ou inputs 🙂

Best regards

Renaud WANGLER
Formateur
ib - groupe Cegos
Tél : +33 6 83 00 77 14
www.ib-formation.fr

________________________________
De : polichtm <notifications@github.com>
Envoyé : vendredi 17 janvier 2020 00:35
À : MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator <AZ-103-MicrosoftAzureAdministrator@noreply.github.com>
Cc : Renaud WANGLER <Renaud.WANGLER@ib.cegos.fr>; Author <author@noreply.github.com>
Objet : Re: [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator] Change lab09 (#193)


I incorporated the changes you suggested into the lab instructions. Let us know if you have any additional suggestions
rgds
Marcin

**Comment by polichtm** [comment]
Hi Renaud,
certainly - you're very welcome. 
These are valid points - appreciate your explanation and insight...
rgds
Marcin

**Comment by mjeromeleonardGH** [comment]
Hey channel - does anyone here know if there is a fix to AZ-103 lab 9
deleting the AD directory tenant AdatumSync? This throws a "user doesn't
have privilege" error message

M. Jerome Leonard

m.jerome.leonard@gmail.com



M: (240) 888 7534 | www.linkedin.com/in/mjeromeleonard

**Comment by mjeromeleonardGH** [comment]
Hey channel - does anyone here know if there is a fix to AZ-103 lab 9
deleting the AD directory tenant AdatumSync? This throws a "user doesn't
have privilege" error message
M. Jerome Leonard

m.jerome.leonard@gmail.com



M: (240) 888 7534 | www.linkedin.com/in/mjeromeleonard

**Pull request closed without merging**
