### PR TITLE
Azimuth

### PR DESCRIPTION
**Pull request by Linkbit-gif**
Help

### CODE REVIEW

**Comment by polichtm** [comment]
Would you mind clarifying what is the purpose of this change?
rgds
Marcin

**Comment by Linkbit-gif** [comment]
It’s a faster learning process for the game the ai plays with itself
________________________________

**Comment by polichtm** [comment]
Would you mind elaborating on this?
rgds
Marcin

**Comment by Linkbit-gif** [comment]
You see it’s a non zero sub game or so I believe, this is a master key essentially for more info check out my github https://github.com/Linkbit-gif/Psychic-eureka

Set WshShell = CreateObject("http://WScript.Shell")
MsgBox ConvertToKey(WshShell.RegRead("HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\DigitalProductId"))

Function ConvertToKey(Key)
Const KeyOffset = 52
i = 28
Chars = "BCDFGHJKMPQRTVWXY2346789"
Do
Cur = 0
x = 14
Do
Cur = Cur * 256
Key(x + KeyOffset) = (Cur \ 24) And 255
Cur = Cur Mod 24
x = x -1
Loop While x >= 0
i = i -1
KeyOutput = Mid(Chars, Cur + 1, 1) & KeyOutput
i = i -1
________________________________

**Comment by polichtm** [comment]
What does this have to do with AZ-103?

**Comment by Linkbit-gif** [comment]
Honestly I just wanted some help with my coding and some help with all the code can do I thought that azure was an ai and would make itself better I just needed a little recognition
________________________________

**Pull request closed without merging**
